version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/" 
    schedule:
      interval: "monthly" 
    commit-message:
      prefix: "maven-version-updates"
    groups:
      minor-and-patch:
        applies-to: version-updates
        patterns:
          - "*" 
        update-types:
        - "minor"
        - "patch"
